spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

docurural:
  cors:
    allowed-origins: http://localhost:4200

logging:
  level:
    co.edu.docurural: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
